---
- hosts: local
  tasks:
   - name: Generate Config files
     template: src=/media/TRAINING/ANSIBLE/GITHUB/week5/access_switch_ex1.j2
               dest=/media/TRAINING/ANSIBLE/GITHUB/week5/OUT/{{item.hostname}}.txt
     with_items:
        - {hostname: pynet-sw1, ip_addr: 9.1.1.1, default_gateway: 9.1.1.255 }
        - {hostname: pynet-sw2, ip_addr: 9.2.1.2, default_gateway: 9.2.1.255 }
        - {hostname: pynet-sw3, ip_addr: 9.3.1.3, default_gateway: 9.3.1.255 }
        - {hostname: pynet-sw4, ip_addr: 9.4.1.4, default_gateway: 9.4.1.255 }
        - {hostname: pynet-sw5, ip_addr: 9.5.1.5, default_gateway: 9.5.1.255 }

