---
# In the above access_switch.j2 template use a Jinja2 for loop to create all
# of the interfaces from FastEthernet 0/1 to FastEthernet 0/24.  Each of the
# interfaces should have the following configuration:
#
# >>>>
# interface FastEthernet 0/X                 # where X is the interface number
#  switchport access vlan {{item.access_vlan}}
#   switchport mode access
#    spanning-tree portfast
# >>>>
#
#
#[angelus@localhost week5]$ tree
#.
#├── access_switch_ex1.j2
#├── access_switch_snmp_ex2.j2
#├── exercise_1.yml
#├── exercise_2.yml
#├── exercise_3.yml
#├── OUT
#└── roles
#    └── switch
#            ├── tasks
#                    │   └── main.yml
#                            ├── templates
#                                    │   └── access_switch_ex3.j2
#                                            └── vars
#                                                        └── main.yml
#
#                                                        6 directories, 8 files
#
#[angelus@localhost week5]$ ansible-playbook exercise_3.yml
# _____________________________________
# < PLAY [Generate configuration files] >
#  -------------------------------------
#
# changed: [localhost] => (item={u'SNMP': True, u'hostname': u'pynet-sw1',
# u'ip_addr': u'9.1.1.1', u'default_gateway': u'9.1.1.255'})
# changed: [localhost] => (item={u'SNMP': False, u'hostname': u'pynet-sw2',
# u'ip_addr': u'9.2.1.2', u'default_gateway': u'9.2.1.255'})
# changed: [localhost] => (item={u'SNMP': True, u'hostname': u'pynet-sw3',
# u'ip_addr': u'9.3.1.3', u'default_gateway': u'9.3.1.255'})
# changed: [localhost] => (item={u'SNMP': False, u'hostname': u'pynet-sw4',
# u'ip_addr': u'9.4.1.4', u'default_gateway': u'9.4.1.255'})
# changed: [localhost] => (item={u'SNMP': True, u'hostname': u'pynet-sw5',
# u'ip_addr': u'9.5.1.5', u'default_gateway': u'9.5.1.255'})
#
# localhost                  : ok=2    changed=1    unreachable=0    failed=0
#
# [angelus@localhost week5]$
#
# [angelus@localhost week5]$ tree
# .
# ├── access_switch_ex1.j2
# ├── access_switch_snmp_ex2.j2
# ├── exercise_1.yml
# ├── exercise_2.yml
# ├── exercise_3.yml
# ├── OUT
# │   ├── pynet-sw1.txt
# │   ├── pynet-sw2.txt
# │   ├── pynet-sw3.txt
# │   ├── pynet-sw4.txt
# │   └── pynet-sw5.txt
# └── roles
#     └── switch
#             ├── tasks
#                     │   └── main.yml
#                             ├── templates
#                                     │   └── access_switch_ex3.j2
#                                             └── vars
#                                                         └── main.yml
#
#                                                         6 directories, 13 files
#
#

- name: Generate configuration files
  hosts: local

  roles:
    - switch
