---
- name: Exercise 2, week 6
  hosts: arista 

  tasks: 
    - name: Set interface Ethernet6  description and make sure it's enabled
      eos_interface: name=Ethernet6 description="*** IN USE ***" enable=yes
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

    - name: Set interface Ethernet6 as access port on vlan 842
      eos_switchport: name=Ethernet6 mode=access access_vlan=842
        username={{ eapi_username }}
        password={{ eapi_password }}
        host={{ eapi_hostname }}
        port={{ eapi_port }}
        transport=https

